import { Context } from 'telegraf';
import { UserModel } from '#modules/auth/user.model';
import { logger } from '#utils/logger';
import { generateUniqueLicense } from './mother.service';

export const handleGenerateLicense = async (ctx: Context): Promise<void> => {
  if (!ctx.from) return;

  try {
    const user = await UserModel.findOne({ telegramId: ctx.from.id }).lean();
    if (user?.role !== 'mother') {
      await ctx.answerCbQuery('❌ شما دسترسی به این بخش را ندارید.', {
        show_alert: true
      });
      return;
    }

    // فراخوانی سرویس ایزوله شده برای تولید لایسنس
    const code = await generateUniqueLicense();

    await ctx.answerCbQuery('✅ لایسنس ۱ ساعته با موفقیت تولید شد!');

    const message =
      `🎯 **کد لایسنس تولید شد**\n\n` +
      `کد زیر را درون ربات کپی کنید و سپس در تاپیک مورد نظر، کلمه <code>start</code> را بفرستید.\n` +
      `⏳ **اعتبار:** دقیقاً ۱ ساعت\n\n` +
      `<code>${code}</code>`;

    await ctx.reply(message, { parse_mode: 'HTML' });
    logger.info(`Temporary 1-hour license generated by mother. Code: ${code}`);
  } catch (error) {
    logger.error('Error generating temporary license:', error);
    await ctx.answerCbQuery('⚠️ خطایی در تولید لایسنس رخ داد.', {
      show_alert: true
    });
  }
};
