// apps/backend/src/modules/telegram-bot/handlers/mother.handler.ts

import { Context } from 'telegraf';
import crypto from 'crypto';
import { UserModel } from '#modules/auth/user.model';
import { TenantModel } from '#modules/tenant/tenant.model';
import { logger } from '#utils/logger';

export const handleGenerateLicense = async (ctx: Context): Promise<void> => {
  if (!ctx.from) return;

  try {
    const user = await UserModel.findOne({ telegramId: ctx.from.id }).lean();
    if (user?.role !== 'mother') {
      await ctx.answerCbQuery('❌ شما دسترسی به این بخش را ندارید.', {
        show_alert: true
      });
      return;
    }

    let code = '';
    let isCreated = false;
    let attempts = 0;
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000);

    // مدیریت Edge Case: حلقه Retry برای جلوگیری از خطای Duplicate Key (11000)
    while (!isCreated && attempts < 3) {
      code = crypto.randomBytes(8).toString('hex').toUpperCase();
      try {
        await TenantModel.create({
          licenseCode: code,
          isBound: false,
          isActive: false,
          expiresAt
        });
        isCreated = true;
      } catch (err: unknown) {
        if (
          typeof err === 'object' &&
          err !== null &&
          'code' in err &&
          (err as { code: number }).code === 11000
        ) {
          attempts++;
        } else {
          throw err; // خطای غیرمرتبط با تکراری بودن کد
        }
      }
    }

    if (!isCreated) {
      throw new Error(
        'Failed to generate a unique license code after 3 attempts.'
      );
    }

    await ctx.answerCbQuery('✅ لایسنس ۱ ساعته با موفقیت تولید شد!');

    const message =
      `🎯 **کد لایسنس تولید شد**\n\n` +
      `کد زیر را درون ربات کپی کنید و سپس در تاپیک مورد نظر، کلمه <code>start</code> را بفرستید.\n` +
      `⏳ **اعتبار:** دقیقاً ۱ ساعت\n\n` +
      `<code>${code}</code>`;

    await ctx.reply(message, { parse_mode: 'HTML' });
    logger.info(`Temporary 1-hour license generated by mother. Code: ${code}`);
  } catch (error) {
    logger.error('Error generating temporary license:', error);
    await ctx.answerCbQuery('⚠️ خطایی در تولید لایسنس رخ داد.', {
      show_alert: true
    });
  }
};
